reserved_usernames:
  - admin
  - administrator
  - support
  - system
  - root
  - help
  - owner
  - webmaster
  - api
  - pinghook
  - slack
  - discord
  - mail
  - contact
  - info
  - moderator
  - developer
  - test
  - testing
  - official
  - terms
  - privacy
  - security
  - public
  - private
  - "null"
  - undefined
  - me
  - you
  - yourname
  - username
  - api-key
  - token
  - webhook
  - post
  - get
  - delete
  - put
  - patch
  - curl
  - mailmaster
  - postmaster
  - abuse
  - hostmaster
  - root
  - webmaster
  - info
  - contact
  - support
  - security
  - mail
  - marketing
  - sales
  - noreply
  - no-reply
  - donotreply
  - system
  - team
  - office
  - billing
  - accounts
  - cs
  - ceo
